// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyivaetjdxubaweepayf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5aXZhZXRqZHh1YmF3ZWVwYXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDAwODMsImV4cCI6MjA2NjQxNjA4M30.w3wnzJwpfRUu5Dl2IPzV9Isc_59NMvnlaLwxjslT4cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);